env:
  global:
    - CC_TEST_REPORTER_ID=85ed34006e87b97e4f0400748d7f654ba2684a2aa62dceed5c9935930ad5fafa

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: swift
      install:
        - ./BuildScripts/osx_install.sh
        - ./BuildScripts/osx_coverage_install.sh
      script: ./BuildScripts/osx_script.sh
      # Coverage delivery to codeclimate setup
      # codeclimate only shows us results of one run, so we just run it once on last xcode release.
      before_script: ./BuildScripts/osx_coverage_before.sh
      after_script: ./BuildScripts/osx_coverage_after.sh

    - os: osx
      osx_image: xcode9.2
      language: swift
      install: ./BuildScripts/osx_install.sh
      script: ./BuildScripts/osx_script.sh

    - os: osx
      osx_image: xcode9.1
      language: swift
      install: ./BuildScripts/osx_install.sh
      script: ./BuildScripts/osx_script.sh
