matrix:
  include:
    - {os: osx, osx_image: xcode9.3beta, language: swift}
    - {os: osx, osx_image: xcode9.2, language: swift}
    - {os: osx, osx_image: xcode9.1, language: swift}
script:
  # Build
  - xcodebuild -project SwiftGraph.xcodeproj -scheme SwiftGraph build-for-testing
  # Test
  - xctool -project SwiftGraph.xcodeproj -scheme SwiftGraph run-tests
